# Site settings
title: The Music Plug
email: themusicplugpage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: /:collection/:path
url: "https://themusicplug.github.com" # the base hostname & protocol for your site
github_username: themusicplug

collections:
  plugins:
    output: true
    permalink: /plugins/:path
    includes:
      - vendor
      - landing

collections_dir: pages

# Build settings
markdown: kramdown
